const fs = require('fs'), path = require('path');
const J = require('./nsga2-fronts.json');
const f = (v) => Math.round(v).toLocaleString('en-US');
const NOTE = { 'AD build': 'Defense = harmonic mean of physical and magic effective HP. DPS = auto-attacks with crit.',
  'AP build': 'Defense = harmonic mean of physical and magic effective HP. DPS = 4 spells on a 7 s base cooldown, (80 + 0.7 AP) each, with cooldown reduction, penetration and Liandry burn.',
  'MR tank': 'Defense = magic effective HP. DPS = bruiser auto-attacks plus Sunfire aura.',
  'Armor tank': 'Defense = physical effective HP. DPS = bruiser auto-attacks plus Sunfire aura.' };
let md = `# Multi-objective builds (NSGA-II): defense vs DPS vs gold\n\n`;
md += `Each archetype is a full **6-item** build. NSGA-II searched for the Pareto front of three goals at once: **maximize defense**, **maximize DPS**, **minimize gold cost**. A build is on the front when no other 6-item build is at least as good on all three and better on one. Generated by \`tools/nsga2.js\` (population ${J.pop}, ${J.gens} generations, ${J.seeds.length} seeds merged, about ${Math.round(Object.values(J.archetypes).reduce((a, r) => a + r.front.length, 0) / 4)} front points per archetype).\n\n`;
md += `**How to read the tables.** Every row is a Pareto point: no 6-item build beats it on defense and DPS without costing more gold. "Balance" means defense x DPS, each scaled 0-1 against that archetype's best on the front. "Defense floor" rows give the most DPS that keeps at least that share of the archetype's best defense.\n\n`;
for (const [name, r] of Object.entries(J.archetypes)) {
  const fr = r.front, maxD = Math.max(...fr.map((x) => x.defense)), maxP = Math.max(...fr.map((x) => x.dps));
  const score = (x) => (x.defense / maxD) * (x.dps / maxP);
  const row = (label, x) => `| ${label} | ${f(x.defense)} | ${f(x.dps)} | ${f(x.cost)} | ${x.items.join(' + ')} |\n`;
  const top = (fn) => fr.filter(fn).sort((a, b) => score(b) - score(a))[0];
  md += `## ${name}\n\n${NOTE[name]}\n\n| Pick | Defense | DPS | Gold | Items |\n|---|---|---|---|---|\n`;
  md += row('Max defense', [...fr].sort((a, b) => b.defense - a.defense || a.cost - b.cost)[0]);
  for (const pct of [0.75, 0.5, 0.25]) { const x = fr.filter((y) => y.defense >= pct * maxD).sort((a, b) => b.dps - a.dps || a.cost - b.cost)[0]; md += row(`Defense floor ${pct * 100}%`, x); }
  md += row('Best balance', top(() => true));
  md += row('Max DPS', [...fr].sort((a, b) => b.dps - a.dps || a.cost - b.cost)[0]);
  // how much defense/dps buys: gold-efficiency frontier snapshot
  md += `\n`;
  const bands = [[0, 8000], [8000, 11000], [11000, 14000], [14000, 17000], [17000, 99999]];
  md += `Best balance within each gold band:\n\n| Gold band | Defense | DPS | Gold | Items |\n|---|---|---|---|---|\n`;
  for (const [lo, hi] of bands) { const x = fr.filter((y) => y.cost >= lo && y.cost < hi).sort((a, b) => score(b) - score(a))[0]; if (x) md += `| ${f(lo)}-${hi > 90000 ? '+' : f(hi)}g | ${f(x.defense)} | ${f(x.dps)} | ${f(x.cost)} | ${x.items.join(' + ')} |\n`; }
  md += `\n`;
}
md += `## Assumptions\n\n- Base stats before items (level 18): AD build ${JSON.stringify({ hp: 1800, armor: 70, mr: 45, ad: 100, as: 0.7 })}, AP build ${JSON.stringify({ hp: 1700, armor: 60, mr: 40 })}, both tanks ${JSON.stringify({ hp: 2100, armor: 100, mr: 50, ad: 80, as: 0.65 })}. DPS targets a ${J.target.hp} HP, ${J.target.armor} armor, ${J.target.mr} MR enemy.\n- Same item rules as the first report: finished items only, one boots, one Sunfire, one jungle item. Guardian Angel counts as +30% max HP and Maw of Malmortius as a 400 magic shield. Stacking items use their base stats.\n- Actives, spellblade procs and auras that help allies are not counted. Guessed numbers: Malady 15 on-hit, Statikk Shiv 100 per 5 attacks, Blade of the Ruined King at 60% target HP.\n- Check: the max-defense and max-DPS ends of the fronts match the exhaustive search in the first report (AD DPS 921, armor tank 28,902, MR tank 22,338).\n`;
fs.writeFileSync(path.join(__dirname, '..', 'docs', 'best-builds-nsga2.md'), md);
