const b = require('./best-builds.json'), s = require('./best-builds.stacked.json');
const f = (v) => Math.round(v).toLocaleString('en-US');
let md = `# Best League Classic (Jade) builds by objective\n\nExhaustive search: every legal combination of finished items (max 1 boots, one Sunfire, one jungle item) for each build size 1-6. Generated by \`tools/optimize.js\`.\n\n`;
for (const [name, r] of Object.entries(b.results)) {
  md += `## ${name}\n\n| Items | ${r.unit} | Gold | Build |\n|---|---|---|---|\n`;
  for (let n = 1; n <= 6; n++) { const x = r.builds[n][0]; md += `| ${n} | ${f(x.v)} | ${f(x.cost)} | ${x.items.join(' + ')} |\n`; }
  md += '\n';
}
md += `## If stacking items are fully stacked\n\nLeviathan 20 stacks (+640 HP, -15% damage), Rod of Ages 10 stacks, Bloodthirster 30 stacks, Sword of the Occult 20 stacks, Manamune full mana.\n\n`;
for (const [name, r] of Object.entries(s.results)) {
  md += `**${name}**\n\n| Items | ${r.unit} | Gold | Build |\n|---|---|---|---|\n`;
  for (let n = 1; n <= 6; n++) { const x = r.builds[n][0]; md += `| ${n} | ${f(x.v)} | ${f(x.cost)} | ${x.items.join(' + ')} |\n`; }
  md += '\n';
}
const a = b.assumptions;
md += `## Assumptions\n\n- Tank at level 18 before items: ${a.TANK.hp} HP, ${a.TANK.armor} armor, ${a.TANK.mr} MR. Score = effective HP = HP x (1 + resist/100). Guardian Angel counts as +30% max HP; Maw of Malmortius as a 400 magic shield; Leviathan's 15% reduction only when stacked.\n- Carry at level 18 before items: ${a.CARRY.ad} AD, ${a.CARRY.as} attack speed, ${a.CARRY.hp} HP, ${a.CARRY.mana} mana. Target: ${a.TARGET.hp} HP, ${a.TARGET.armor} armor, ${a.TARGET.mr} MR. Attack speed capped at ${a.AS_CAP}.\n- DPS = sustained auto-attack damage per second: attack damage, attack speed, crit (200% crits, 250% with Infinity Edge), armor penetration (Last Whisper 35%, Black Cleaver 25% reduction + 10 lethality, Youmuu's 20 lethality) and on-hit damage. Spellblades, spell damage and item actives are not counted.\n- Values not in the item text and assumed: Malady 15 magic on-hit, Statikk Shiv 100 magic per 5 attacks, Blade of the Ruined King at 60% target HP, Guinsoo's at 8 stacks, Sword of the Divine passive 45% attack speed.\n`;
require('fs').writeFileSync(require('path').join(__dirname, '..', 'docs', 'best-builds.md'), md);
